### ISSUE TITLE
The scaling factor for distance restraints

### ISSUE THREAD

**Issue by SHZ66** [tjs23/nuc_dynamics#2]
Hi,

It seems that the target distance is obtained by dist = scale * (binned_contacts) ** pow, where pow is set to -0.33 and scale is set to 1.0 by default. So that the maximum distance will be 1.0 (I assume the unit is bead radius), which seems to be too small. My question is should I choose a different scale? In reality, how do I estimate the value for scale?

Thank you,
She

**Comment by tjs23** [comment]
The distance of 1.0 particle radii is not too small, but it's precise value is somewhat arbitrary. The restraint scale value does not need to be changed. It has only ever been optimised with regard to overall annealing convergence, and in these tests the value merely needs to be about the same size as the particle. Here the purpose of the Hi-C contacts, represented as distance restraints, is simply to make a force so that particles touch, if there is evidence. This software is not for canonical/population Hi-C where you might want to restrain longer distances. It is only for single-cell Hi-C where you know regions really are spatially adjacent in a single structure. Hence, all the restraint distances are small on the model scale. 
The overall approach taken is to make few assumptions and let the single-cell Hi-C data drive the folded conformation. Accordingly, only a backbone path, a repulsive term and the Hi-C contacts are employed. In the current implementation the Hi-C contacts attempt to pull particles together so that they touch, i.e. to their repulsive radii, without much overlap. The power scaling with Hi-C contact count is designed to increase annealing force (to aid minimisation) where there is more evidence, rather than affect the structure much. This applies mostly to early low resolution calculations with large bin/segment sizes. Given the calculation is dealing with a course approximation of chromatin segments (typically each final particle is 100 kb) and the actual Hi-C ligation(s) could be anywhere within the segment (which really is a 3D path of chromatin of unknown shape), so setting the contact distance to be similar in scale to the segmental distance reflects this uncertainty. 
Beyond an overall scaling there doesn't seem to be a particularly objective way to parametrise the details of the force field. However, future versions of the nuc_dynamics software will handle the matter of overall scaling so that when the number of particles (resolution) changes the absolute coordinate size stays the same, which in turn can be matched to values from microscopy.

**Comment by SHZ66** [comment]
It makes sense. Thank you for your reply.
