### ISSUE TITLE
Parameter suggestions for small genomes

### ISSUE THREAD

**Issue by aakashsur** [tjs23/nuc_dynamics#3]
Hi, we are working with a smaller genome (32mb) with 36 chromosomes ranging from 300kb to 2.5mb. What parameters would you suggest changing for a genome of this size. From what I can tell, the default parameters are really meant for human sized genome.

**Comment by tjs23** [comment]
The only thing that would definitely need to be tweaked is the particle sizes (-s), though this naturally depends on the data density, i.e. structures can be calulated to higher resolution with more data. As a rough guide I recommend setting the highest resolution so that at least 80% of particles have one or more contact. For chromosomes in the size range you mention maybe try something like `-s 0.1 0.05 0.025 0.01` , i.e. 100 kb down to a final resolution of 10 kb, assumig that is appropriate.
