### ISSUE TITLE
Why there are some stick like structure in the result

### ISSUE THREAD

**Issue by Nanguage** [tjs23/nuc_dynamics#6]
Hi,

I use this software to simulate 3d structure according to the single cell Hi-C data produced by our lab.
The data has about 30,000 contact in a single cell(range from 30,000 to 120,000), and the reference genome is hg19.
I use the default parameter `-s 8.0 4.0 2.0 1.0 0.4 0.2 0.1` to run the software.
But when I check the result (using pymol to open the pdb file), I found in every cell's structure, there are a strick like
structure, like this:

![image](https://user-images.githubusercontent.com/14010939/92238367-acad8680-eeeb-11ea-85aa-1e6c466407d1.png)

And the shape of structure are not very round like the pictures in the paper. I can't understand this.
It's it because the contacts are not sufficient? Or something else?

**Comment by tjs23** [comment]
Firstly, to check whether the contacts are sufficient to generate consistent structures you would need to generate multiple coordinate models and look at how well they align.
Regarding the stick-like structure, I suspect that this is specific to a couple of the chromosomes; you may like to check this for different cells. My first guess is that there is a problem with the output formatting, maybe triggered by the chromosome naming,  such that the x,y,z coordinate columns don't align. Please send me an example PDB file directly so that I may investigate further.

**Comment by Nanguage** [comment]
Thanks for your response. I have found the reason. It's indeed caused by chromosome name character overflow in my modified version of your script. I'm not noticed that the PDB is a fixed column-width format before. I have fixed it. Thanks!
